
/* Table: FIM_EVENTOS, Owner: SYSDBA */

CREATE TABLE "FIM_COLETORES" 
(
  "IDCAMP"	     INTEGER NOT NULL,
  "IDPROVA"	     INTEGER NOT NULL,
  "IDMAQ"	     VARCHAR(12) NOT NULL,
  "SEQUENCIA"	 INTEGER,
  "MAQUINA"	     INTEGER,
  "NUMERO"	     INTEGER,
  "HORASHMSC"    VARCHAR(11),
  "HORASCENTESSIMOS" VARCHAR(7),
  "HORASHMSD"    VARCHAR(11),
  "HORASDECIMOS" VARCHAR(7),
  "HORASHMS"    VARCHAR(11),
  "HORASNORMAL" VARCHAR(7),
  "HORATOQUE"	VARCHAR(7),
  "ORIGEMPI"	VARCHAR(10),
CONSTRAINT "PK_FIM_COLETORES" PRIMARY KEY ("IDCAMP", "IDPROVA","IDMAQ")
);