
/* Table: EVENTOS, Owner: SYSDBA */

CREATE TABLE "FIM_EVENTOS" 
(
  "ID"	 INTEGER NOT NULL,
  "IDCAMPEONATO" INTEGER NOT NULL,
  "NOME"	     VARCHAR(40) NOT NULL,
  "CIRCUITO"     VARCHAR(30),
  "MUNICIPIO"	 VARCHAR(40) NOT NULL,
  "LOCALIDADE"	 VARCHAR(20),
  "DATA"	     DATE NOT NULL,
  "NUMEROVOLTAS" INTEGER DEFAULT 0 NOT NULL,
  "NUMEROETAPAS"	 INTEGER DEFAULT 0 NOT NULL,
CONSTRAINT "PK_FIM_EVENTOS" PRIMARY KEY ("ID", "IDCAMPEONATO")
);