/* Table: CATEGORIAS, Owner: SYSDBA */

CREATE TABLE "CATEGORIAS" 
(
  "ID"	 CHAR(3) NOT NULL,
  "IDCAMP"	 INTEGER NOT NULL,
  "DESCRICAO"	 VARCHAR(20) NOT NULL,
  "INTERVALOENTRECAT"	 TIME NOT NULL,
  "NUMERALINICIAL"	 INTEGER NOT NULL,
  "ORDEMIMPRESSAO"	 INTEGER NOT NULL,
  "COR"	 VARCHAR(15) NOT NULL,
CONSTRAINT "PK_CATEGORIAS" PRIMARY KEY ("ID")
);