
/* Table: CAMPEONATOS, Owner: SYSDBA */

CREATE TABLE "CAMPEONATOS" 
(
  "ID"	 INTEGER NOT NULL,
  "DESCRICAO"	 VARCHAR(70) NOT NULL,
  "ETAPA"	 INTEGER NOT NULL,
  "CAMP1"	 CHAR(3) NOT NULL,
  "CAMP2"	 CHAR(3),
  "CAMP3"	 CHAR(3),
CONSTRAINT "PK_CAMPEONATOS" PRIMARY KEY ("ID")
);