
/* Table: EVENTOS, Owner: SYSDBA */

CREATE TABLE "EVENTOS" 
(
  "UD"	 INTEGER NOT NULL,
  "IDCAMP"	 INTEGER NOT NULL,
  "DESCRICAO"	 VARCHAR(70) NOT NULL,
  "MUNICIPIO"	 VARCHAR(40) NOT NULL,
  "UF"	 CHAR(2) NOT NULL,
  "DATA"	 DATE NOT NULL,
  "QTDVOLTAS"	 INTEGER NOT NULL,
  "QTDETP"	 INTEGER NOT NULL,
CONSTRAINT "PK_EVENTOS" PRIMARY KEY ("UD")
);